export const FLAG_POSTING_ACTION = 'FLAG_POSTING_ACTION';
export const POST_ACTION = 'POST_ACTION';
export const POST_ACTION_SUCCEEDED = 'POST_ACTION_SUCCEEDED';
export const POST_ACTION_FAILED = 'POST_ACTION_FAILED';
