export const SET_CODE = 'SET_CODE';
export const SET_HEADER_CODE = 'SET_HEADER_CODE';
export const SET_FOOTER_CODE = 'SET_FOOTER_CODE';
export const RUN_CODE_SUCCEEDED = 'RUN_CODE_SUCCEEDED';
export const RUN_CODE_FAILED = 'RUN_CODE_FAILED';
export const PRINT_OUTPUT = 'PRINT_OUTPUT';
export const CLEAR_OUTPUT = 'CLEAR_OUTPUT';
