export const SET_PROGRAMMING_LANGUAGE = 'SET_PROGRAMMING_LANGUAGE';
export const SET_CODE = 'SET_CODE';
export const SET_HEADER_CODE = 'SET_HEADER_CODE';
export const SET_DEFAULT_CODE = 'SET_DEFAULT_CODE';
export const SET_FOOTER_CODE = 'SET_FOOTER_CODE';
export const RUN_CODE = 'RUN_CODE';
export const RUN_CODE_SUCCEEDED = 'RUN_CODE_SUCCEEDED';
export const RUN_CODE_FAILED = 'RUN_CODE_FAILED';
export const PRINT_OUTPUT = 'PRINT_OUTPUT';
export const CLEAR_OUTPUT = 'CLEAR_OUTPUT';

export const SET_INPUT = 'SET_INPUT';
export const APPEND_INPUT = 'APPEND_INPUT';
export const SEND_INPUT = 'SEND_INPUT';

export const REGISTER_WORKER_SUCCEEDED = 'REGISTER_WORKER_SUCCEEDED';
export const REGISTER_WORKER_FAILED = 'REGISTER_WORKER_FAILED';
