export const DELETE_FILE_SUCCEEDED = 'DELETE_FILE_SUCCEEDED';
export const DELETE_FILE_FAILED = 'DELETE_FILE_FAILED';
export const GET_FILE_SUCCEEDED = 'GET_FILE_SUCCEEDED';
export const GET_FILE_FAILED = 'GET_FILE_FAILED';
export const GET_FILES_SUCCEEDED = 'GET_FILES_SUCCEEDED';
export const GET_FILES_FAILED = 'GET_FILES_FAILED';
