// settings
export const OPEN_SETTINGS = 'OPEN_SETTINGS';
export const CLOSE_SETTINGS = 'CLOSE_SETTINGS';
export const OPEN_INPUT_SETTINGS = 'OPEN_INPUT_SETTINGS';
export const CLOSE_INPUT_SETTINGS = 'CLOSE_INPUT_SETTINGS';
