// settings
export const OPEN_SETTINGS = 'OPEN_SETTINGS';
export const CLOSE_SETTINGS = 'CLOSE_SETTINGS';
export const OPEN_INPUT_SETTINGS = 'OPEN_INPUT_SETTINGS';
export const CLOSE_INPUT_SETTINGS = 'CLOSE_INPUT_SETTINGS';
export const OPEN_FILE_SETTINGS = 'OPEN_FILE_SETTINGS';
export const CLOSE_FILE_SETTINGS = 'CLOSE_FILE_SETTINGS';
export const OPEN_INPUT_PROMPT = 'OPEN_INPUT_PROMPT';
export const CLOSE_INPUT_PROMPT = 'CLOSE_INPUT_PROMPT';
